import { randomBytes, scrypt, timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { isUniqueViolation, query, transaction } from './db';
import { ROLES } from './roles';
import { ACCOUNT_STATUS, canBuyPlan } from './accountStatus';
import { seedDefaultCars } from './defaultCars';

const scryptAsync = promisify(scrypt) as (password: string, salt: Buffer, keylen: number) => Promise<Buffer>;

const KEY_LENGTH = 64;

export type User = {
  id: number;
  userName: string;
  emailAddress: string;
  accountStatus: string;
  signupDate: string | null;
  subscriptionEndDate: string | null;
  stripeSubscriptionId: string | null;
  // One of ROLES
  role: string;
};

const USER_COLUMNS =
  'id, user_name, email_address, account_status, signup_date, subscription_end_date, stripe_subscription_id, role';

// The site owner is made Admin on sign-up; everyone else is a User
export const OWNER_EMAIL = 'darinlutz@yahoo.com';

// Dates are stored as ISO 8601 UTC strings, so they compare correctly as text.
// One month from `from`, clamped so Jan 31 becomes Feb 28/29 rather than Mar 3.
export function oneMonthFrom(from: Date = new Date()): string {
  const end = new Date(from);
  end.setUTCDate(1);
  end.setUTCMonth(end.getUTCMonth() + 1);
  const lastDay = new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth() + 1, 0)).getUTCDate();
  end.setUTCDate(Math.min(from.getUTCDate(), lastDay));
  return end.toISOString();
}

export function canBuy(user: User, plan: 'monthly' | 'lifetime'): boolean {
  return canBuyPlan(user.accountStatus, plan);
}

export class EmailTakenError extends Error {
  constructor() {
    super('An account with that email address already exists');
  }
}

let schemaReady: Promise<void> | null = null;

// The racingcoach schema holds the site's accounts and everything tied to one:
// Users, each user's own Friends, Tracks and their FocusAreas, CarData, IRacePlanConnections
// and synced RaceResults, DiscordConnections, sign-in Sessions, PasswordResets links and
// CancellationReason feedback.
export function ensureUserSchema(): Promise<void> {
  if (!schemaReady) {
    schemaReady = transaction(async (client) => {
      // Concurrent CREATE ... IF NOT EXISTS can still collide in Postgres
      // when several server instances boot at once, so serialize them.
      await client.query("SELECT pg_advisory_xact_lock(hashtext('racingcoach_user_schema'))");
      await client.query('CREATE SCHEMA IF NOT EXISTS racingcoach');
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."Users" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_name TEXT NOT NULL,
        email_address TEXT NOT NULL,
        password TEXT NOT NULL,
        account_status TEXT NOT NULL DEFAULT '${ACCOUNT_STATUS.unsubscribed}',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        stripe_customer_id TEXT,
        stripe_subscription_id TEXT,
        signup_date TEXT,
        subscription_end_date TEXT,
        role TEXT NOT NULL DEFAULT '${ROLES.user}'
      )`);
      // Email addresses are unique regardless of case
      await client.query(
        'CREATE UNIQUE INDEX IF NOT EXISTS users_email_address_key ON racingcoach."Users" (lower(email_address))'
      );
      await client.query(
        'CREATE INDEX IF NOT EXISTS users_stripe_subscription_id_idx ON racingcoach."Users" (stripe_subscription_id)'
      );
      // Each friend belongs to one user. `seq` records insertion order for listing.
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."Friends" (
        id TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES racingcoach."Users"(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        country TEXT NOT NULL,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        seq BIGINT GENERATED BY DEFAULT AS IDENTITY
      )`);
      await client.query('CREATE INDEX IF NOT EXISTS friends_user_id_idx ON racingcoach."Friends" (user_id, seq)');
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."Sessions" (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES racingcoach."Users"(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query('CREATE INDEX IF NOT EXISTS sessions_user_id_idx ON racingcoach."Sessions" (user_id)');
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."PasswordResets" (
        token_hash TEXT PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES racingcoach."Users"(id) ON DELETE CASCADE,
        expires_at BIGINT NOT NULL
      )`);
      await client.query(
        'CREATE INDEX IF NOT EXISTS password_resets_user_id_idx ON racingcoach."PasswordResets" (user_id)'
      );
      // Each user's own tracks. track_key is the iRacing track key (e.g. "monza full") and track_name
      // the name Garage 61 puts in its CSV file names (TrackFileName); both are unique per user.
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."Tracks" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES racingcoach."Users"(id) ON DELETE CASCADE,
        track_key TEXT NOT NULL,
        track_name TEXT NOT NULL,
        track_length_feet INTEGER CHECK (track_length_feet > 0),
        notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);
      await client.query(
        'CREATE UNIQUE INDEX IF NOT EXISTS tracks_user_id_track_key_key ON racingcoach."Tracks" (user_id, lower(track_key))'
      );
      await client.query(
        'CREATE UNIQUE INDEX IF NOT EXISTS tracks_user_id_track_name_key ON racingcoach."Tracks" (user_id, lower(track_name))'
      );
      // Up to 8 focus areas per track: position runs 1-8 in order around the lap and is unique per track.
      // start_point/end_point are fractions of a lap (LapDistPct). The brake and on-throttle points are
      // feet from the start/finish line and max_brake_pct is a percent; NULL means no target is set.
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."FocusAreas" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        track_id INTEGER NOT NULL REFERENCES racingcoach."Tracks"(id) ON DELETE CASCADE,
        position SMALLINT NOT NULL CHECK (position BETWEEN 1 AND 8),
        name TEXT NOT NULL,
        start_point DOUBLE PRECISION NOT NULL CHECK (start_point >= 0 AND start_point <= 1),
        end_point DOUBLE PRECISION NOT NULL CHECK (end_point >= 0 AND end_point <= 1),
        notes TEXT,
        brake_point_feet INTEGER CHECK (brake_point_feet >= 0),
        max_brake_pct SMALLINT CHECK (max_brake_pct BETWEEN 0 AND 100),
        throttle_point_feet INTEGER CHECK (throttle_point_feet >= 0),
        CHECK (start_point < end_point),
        UNIQUE (track_id, position)
      )`);
      // Each user's own iRacePlan API key (Settings > API Keys on iraceplan.com) and their iRacing
      // customer ID, read from iRacePlan when the key is saved
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."IRacePlanConnections" (
        user_id INTEGER PRIMARY KEY REFERENCES racingcoach."Users"(id) ON DELETE CASCADE,
        api_key TEXT NOT NULL,
        iracing_customer_id INTEGER NOT NULL,
        iracing_name TEXT NOT NULL,
        connected_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        synced_at TIMESTAMPTZ
      )`);
      // One row per race result synced from iRacePlan (one per planning). Positions are 1-based, lap
      // times are in seconds, and NULL means iRacePlan did not report the value. has_result is false for
      // races iRacePlan has no result for this driver in, so they are not fetched again.
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."RaceResults" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES racingcoach."Users"(id) ON DELETE CASCADE,
        iraceplan_planning_id BIGINT NOT NULL,
        start_time TIMESTAMPTZ NOT NULL,
        series TEXT NOT NULL,
        category TEXT,
        track TEXT NOT NULL,
        car TEXT NOT NULL,
        team_race BOOLEAN NOT NULL DEFAULT false,
        has_result BOOLEAN NOT NULL DEFAULT true,
        old_irating INTEGER,
        new_irating INTEGER,
        old_safety_rating REAL,
        new_safety_rating REAL,
        start_position INTEGER,
        finish_position INTEGER,
        laps_complete INTEGER,
        laps_led INTEGER,
        incidents INTEGER,
        best_lap_seconds REAL,
        average_lap_seconds REAL,
        reason_out TEXT,
        synced_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (user_id, iraceplan_planning_id)
      )`);
      await client.query(
        'ALTER TABLE racingcoach."RaceResults" ADD COLUMN IF NOT EXISTS has_result BOOLEAN NOT NULL DEFAULT true'
      );
      await client.query(
        'CREATE INDEX IF NOT EXISTS race_results_user_id_start_time_idx ON racingcoach."RaceResults" (user_id, start_time)'
      );
      // Each user's own cars: dimensions in inches, weights in pounds (wet weight includes the driver),
      // displacement in liters. car_name is unique per user; NULL means the value is not known.
      const [{ car_data_missing: carDataMissing }] = (
        await client.query(`SELECT to_regclass('racingcoach."CarData"') IS NULL AS car_data_missing`)
      ).rows;
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."CarData" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER NOT NULL REFERENCES racingcoach."Users"(id) ON DELETE CASCADE,
        car_name TEXT NOT NULL,
        length_in DOUBLE PRECISION CHECK (length_in > 0),
        width_in DOUBLE PRECISION CHECK (width_in > 0),
        wheelbase_in DOUBLE PRECISION CHECK (wheelbase_in > 0),
        dry_weight_lbs INTEGER CHECK (dry_weight_lbs > 0),
        wet_weight_lbs INTEGER CHECK (wet_weight_lbs > 0),
        displacement_liters DOUBLE PRECISION CHECK (displacement_liters > 0),
        rpm_limit INTEGER CHECK (rpm_limit > 0),
        torque_lb_ft INTEGER CHECK (torque_lb_ft > 0),
        power_bhp INTEGER CHECK (power_bhp > 0),
        notes TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);
      await client.query(
        'CREATE UNIQUE INDEX IF NOT EXISTS car_data_user_id_car_name_key ON racingcoach."CarData" (user_id, lower(car_name))'
      );
      // New accounts get the default cars when they sign up (createUser); accounts that existed
      // before the table did get them once, here
      if (carDataMissing) await seedDefaultCars(client, null);
      // Why each monthly subscriber canceled, one row per cancellation. The user's name and email are
      // copied in so the record survives the account being deleted (user_id is then set NULL).
      // reason is one of CANCELLATION_REASONS' labels; stripe_subscription_id is the confirmation number.
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."CancellationReason" (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER REFERENCES racingcoach."Users"(id) ON DELETE SET NULL,
        user_name TEXT NOT NULL,
        email_address TEXT NOT NULL,
        canceled_at TIMESTAMPTZ NOT NULL,
        reason TEXT NOT NULL,
        notes TEXT,
        stripe_subscription_id TEXT NOT NULL,
        subscription_end_date TEXT
      )`);
      await client.query(
        'CREATE INDEX IF NOT EXISTS cancellation_reason_user_id_idx ON racingcoach."CancellationReason" (user_id)'
      );
      // Each user's linked Discord account (Discord OAuth2, identify scope). A Discord account can be
      // linked to only one user. No Discord tokens are kept.
      await client.query(`CREATE TABLE IF NOT EXISTS racingcoach."DiscordConnections" (
        user_id INTEGER PRIMARY KEY REFERENCES racingcoach."Users"(id) ON DELETE CASCADE,
        discord_user_id TEXT NOT NULL UNIQUE,
        discord_username TEXT NOT NULL,
        discord_global_name TEXT,
        discord_avatar TEXT,
        connected_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )`);
    }).catch((error) => {
      schemaReady = null;
      throw error;
    });
  }
  return schemaReady;
}

// Stored as "scrypt$<salt hex>$<hash hex>" so the format is self-describing.
async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16);
  const hash = await scryptAsync(password, salt, KEY_LENGTH);
  return `scrypt$${salt.toString('hex')}$${hash.toString('hex')}`;
}

async function verifyPassword(password: string, stored: string): Promise<boolean> {
  const [scheme, saltHex, hashHex] = stored.split('$');
  if (scheme !== 'scrypt' || !saltHex || !hashHex) return false;
  const expected = Buffer.from(hashHex, 'hex');
  const actual = await scryptAsync(password, Buffer.from(saltHex, 'hex'), expected.length);
  return timingSafeEqual(actual, expected);
}

function rowToUser(row: Record<string, unknown>): User {
  return {
    id: Number(row.id),
    userName: row.user_name as string,
    emailAddress: row.email_address as string,
    accountStatus: row.account_status as string,
    role: row.role as string,
    signupDate: (row.signup_date as string | null) ?? null,
    subscriptionEndDate: (row.subscription_end_date as string | null) ?? null,
    stripeSubscriptionId: (row.stripe_subscription_id as string | null) ?? null,
  };
}

function initialRole(emailAddress: string): string {
  return emailAddress.trim().toLowerCase() === OWNER_EMAIL ? ROLES.admin : ROLES.user;
}

export async function createUser(input: {
  userName: string;
  emailAddress: string;
  password: string;
}): Promise<User> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(input.password);
  try {
    // The account starts with its own copy of the default cars to edit in the Car Data tab
    return await transaction(async (client) => {
      const { rows } = await client.query(
        `INSERT INTO racingcoach."Users" (user_name, email_address, password, account_status, signup_date, role)
         VALUES ($1, $2, $3, $6, $4, $5)
         RETURNING ${USER_COLUMNS}`,
        [input.userName, input.emailAddress, passwordHash, new Date().toISOString(), initialRole(input.emailAddress), ACCOUNT_STATUS.unsubscribed]
      );
      const user = rowToUser(rows[0]);
      await seedDefaultCars(client, user.id);
      return user;
    });
  } catch (error) {
    if (isUniqueViolation(error)) {
      throw new EmailTakenError();
    }
    throw error;
  }
}

// Returns the user only when the email exists and the password matches.
export async function authenticateUser(emailAddress: string, password: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(
    `SELECT ${USER_COLUMNS}, password FROM racingcoach."Users" WHERE lower(email_address) = lower($1)`,
    [emailAddress]
  );
  if (!row) return null;
  const ok = await verifyPassword(password, row.password as string);
  return ok ? rowToUser(row) : null;
}

export async function getUserByEmail(emailAddress: string): Promise<User | null> {
  await ensureUserSchema();
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM racingcoach."Users" WHERE lower(email_address) = lower($1)`, [
    emailAddress,
  ]);
  return row ? rowToUser(row) : null;
}

// Also signs the user out everywhere, since an old session may belong to
// whoever knew the previous password.
export async function updatePassword(userId: number, password: string): Promise<void> {
  await ensureUserSchema();
  const passwordHash = await hashPassword(password);
  await transaction(async (client) => {
    await client.query('UPDATE racingcoach."Users" SET password = $1 WHERE id = $2', [passwordHash, userId]);
    await client.query('DELETE FROM racingcoach."Sessions" WHERE user_id = $1', [userId]);
  });
}

export async function getUserById(id: number): Promise<User | null> {
  await ensureUserSchema();
  // A monthly subscription whose end date has passed (e.g. a failed renewal) is expired
  await query(
    `UPDATE racingcoach."Users" SET account_status = $3
     WHERE id = $1 AND account_status = $4 AND subscription_end_date < $2`,
    [id, new Date().toISOString(), ACCOUNT_STATUS.expired, ACCOUNT_STATUS.monthly]
  );
  const [row] = await query(`SELECT ${USER_COLUMNS} FROM racingcoach."Users" WHERE id = $1`, [id]);
  return row ? rowToUser(row) : null;
}

// Stripe purchases only change account_status; the role (Admin or User)
// never changes with a subscription.

// Links a completed Checkout Session to the user who started it.
export async function startSubscription(
  userId: number,
  stripeCustomerId: string,
  stripeSubscriptionId: string
): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE racingcoach."Users" SET stripe_customer_id = $1, stripe_subscription_id = $2, account_status = $5,
       subscription_end_date = $3
     WHERE id = $4`,
    [stripeCustomerId, stripeSubscriptionId, oneMonthFrom(), userId, ACCOUNT_STATUS.monthly]
  );
}

// A paid Lifetime purchase never expires. Clearing the subscription ID keeps
// events from an earlier monthly subscription from changing the status.
// Returns that earlier monthly subscription's ID, if any, so the caller can
// cancel it in Stripe.
export async function grantLifetimeAccess(
  userId: number,
  stripeCustomerId: string | null
): Promise<string | null> {
  await ensureUserSchema();
  const [row] = await query(
    `UPDATE racingcoach."Users" AS u SET account_status = $3, subscription_end_date = NULL,
       stripe_subscription_id = NULL, stripe_customer_id = COALESCE($1, u.stripe_customer_id)
     FROM (SELECT id, stripe_subscription_id FROM racingcoach."Users" WHERE id = $2) AS previous
     WHERE u.id = previous.id
     RETURNING previous.stripe_subscription_id AS previous_subscription_id`,
    [stripeCustomerId, userId, ACCOUNT_STATUS.lifetime]
  );
  return (row?.previous_subscription_id as string | null | undefined) ?? null;
}

// Called on each successful monthly renewal payment.
export async function renewSubscription(stripeSubscriptionId: string): Promise<void> {
  await ensureUserSchema();
  await query(
    `UPDATE racingcoach."Users" SET account_status = $3, subscription_end_date = $1
     WHERE stripe_subscription_id = $2`,
    [oneMonthFrom(), stripeSubscriptionId, ACCOUNT_STATUS.monthly]
  );
}

// After Stripe has canceled the user's monthly subscription: marks the account Canceled (keeping
// subscription_end_date, the end of the paid month) and saves why they canceled.
export async function recordCancellation(
  user: User,
  cancellation: { reason: string; notes: string | null; canceledAt: string; stripeSubscriptionId: string }
): Promise<void> {
  await ensureUserSchema();
  await transaction(async (client) => {
    await client.query('UPDATE racingcoach."Users" SET account_status = $1 WHERE id = $2', [
      ACCOUNT_STATUS.canceled,
      user.id,
    ]);
    await client.query(
      `INSERT INTO racingcoach."CancellationReason"
         (user_id, user_name, email_address, canceled_at, reason, notes, stripe_subscription_id, subscription_end_date)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
      [
        user.id,
        user.userName,
        user.emailAddress,
        cancellation.canceledAt,
        cancellation.reason,
        cancellation.notes,
        cancellation.stripeSubscriptionId,
        user.subscriptionEndDate,
      ]
    );
  });
}

export async function setStatusBySubscriptionId(
  stripeSubscriptionId: string,
  accountStatus: string
): Promise<void> {
  await ensureUserSchema();
  await query('UPDATE racingcoach."Users" SET account_status = $1 WHERE stripe_subscription_id = $2', [
    accountStatus,
    stripeSubscriptionId,
  ]);
}
